//EVALUACION TEMA 1
/* const prompt=require
class cooperativa{
   constructor(nombre,edad, apellido, rfc, direccion, telefono,hrustra,cosxhra){
    this._nombre=nombre;
    this._apellido=apellido;
    this._rfc=rfc;
    this._direccion=direccion;
    this._telefono=telefono;
    this._edad=edad;
    this._hrustra=hrustra; 
    this._agregarEm=[]
    this._suelado=0;
    this._cosxhra=cosxhra
   }
   //getter
   //setter
   agregarEmp () {

    let tam =parseInt(prompt("cantidad de empleados "))
    for(let i=0; i <tam; i++){
      this._nombre=prompt("Ingresar el nombre del empleados")  
      this._hrustra=parseInt(prompt("Numero de horas trabajadas"))
      this._cosxhra=parseInt(prompt("ingrese el costo"))
    
    let empleado={
        nombre: this._nombre,
        hrustra: this._hrustra,
        cosxhra: this._cosxhra,
        sueldo: this.calcularSueldo(),
    }
    };
    this._agregarEm.push(empleados);
   }


   EliminarEmp(){
    this._agregarEm.length>0
    ? this._agregarEm.pop()
    : console.log("No hay registro que eliminar");

   }
   calcularSueldo () {
   if (this._hrustra){
    this._sueldo = this._cosxhra * this._hrustra;
    return this._sueldo =
    this._sueldo+(this._cosxhra * porc * (this._hrustra-8))

   }else{
    return (this._sueldo = this._cosxhra * this._hrustra);
   }
}

mostrarEmpleados(){
    this._agregarEm.map((emp) => {
      console.log(
        `El nombre es ${emp.nombre}y tiene un sueldo ${emp.nombre} y tiene un sueldo ${emp.sueldo}`);
    })


}
menuLista(){
    let lista=parseInt(prompt("Que desea hacer: 1 Agregar, 2. Mostrar, 3. "))
}
}

let empleados=new cooperativa();
empleados.agregarEmp();
empleados.mostrarEmpleados();
empleados.EliminarEmp(); */
